import { Pool } from 'pg';
import axios from 'axios';
import dotenv from 'dotenv';

dotenv.config();

const dbHost = process.env.POSTGRES_HOST || 'localhost';
const dbPort = parseInt(process.env.POSTGRES_PORT || '5432');
const dbUser = process.env.POSTGRES_USER || 'postgres';
const dbPassword = process.env.POSTGRES_PASSWORD || 'postgrespassword';
const dbName = process.env.POSTGRES_DB || 'postgres';

export const pool = new Pool({
  host: dbHost,
  port: dbPort,
  user: dbUser,
  password: dbPassword,
  database: dbName,
});

// Helper to resolve templates like {{steps.step_name.output.key}}
function resolveTemplates(config: any, previousOutputs: Record<string, any>): any {
  if (typeof config === 'string') {
    return config.replace(/\{\{steps\.([^.]+)\.output\.([^}]+)\}\}/g, (match, stepName, key) => {
      const stepOutput = previousOutputs[stepName];
      if (stepOutput && stepOutput[key] !== undefined) {
        return typeof stepOutput[key] === 'object' ? JSON.stringify(stepOutput[key]) : String(stepOutput[key]);
      }
      return match;
    });
  } else if (Array.isArray(config)) {
    return config.map(item => resolveTemplates(item, previousOutputs));
  } else if (typeof config === 'object' && config !== null) {
    const resolved: any = {};
    for (const key in config) {
      resolved[key] = resolveTemplates(config[key], previousOutputs);
    }
    return resolved;
  }
  return config;
}

// Call Gemini API or fall back to high-fidelity mock
async function callLLM(prompt: string, attempt = 1): Promise<any> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    // Artificial delay to simulate LLM call
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Smart mock response generation based on prompt keywords
    const lowerPrompt = prompt.toLowerCase();
    let text = "I have processed your prompt. (Simulated LLM response)";
    let sentiment = "neutral";
    let status = "approved";

    if (lowerPrompt.includes("sentiment")) {
      if (lowerPrompt.includes("great") || lowerPrompt.includes("happy") || lowerPrompt.includes("approve")) {
        sentiment = "positive";
        text = "This review is highly positive and expresses extreme satisfaction.";
      } else if (lowerPrompt.includes("bad") || lowerPrompt.includes("error") || lowerPrompt.includes("reject")) {
        sentiment = "negative";
        text = "This review is negative and contains complaints.";
      } else {
        sentiment = "neutral";
        text = "The text has a neutral tone.";
      }
    } else if (lowerPrompt.includes("spam")) {
      text = lowerPrompt.includes("buy cheap coins") ? "SPAM" : "HAM";
    } else if (lowerPrompt.includes("reject")) {
      status = "rejected";
      text = "Rejecting workflow run due to key request details.";
    } else if (lowerPrompt.includes("approve")) {
      status = "approved";
      text = "Approved automatically based on input criteria.";
    }

    return { text, sentiment, status, info: "Generated by high-fidelity local LLM simulation (no GEMINI_API_KEY set)" };
  }

  try {
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        contents: [{ parts: [{ text: prompt }] }]
      },
      {
        headers: { 'Content-Type': 'application/json' },
        timeout: 10000,
      }
    );
    const text = response.data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
    return { text };
  } catch (error: any) {
    if (attempt < 2) {
      console.log(`LLM Call failed, retrying attempt 2... Error: ${error.message}`);
      await new Promise(resolve => setTimeout(resolve, 1000));
      return callLLM(prompt, attempt + 1);
    }
    throw error;
  }
}

// Make HTTP request with retries
async function makeHTTPRequest(config: { url: string; method: string; headers?: any; data?: any }, attempt = 1): Promise<any> {
  try {
    const response = await axios({
      url: config.url,
      method: config.method || 'GET',
      headers: config.headers || {},
      data: config.data || undefined,
      timeout: 10000,
    });
    return {
      status: response.status,
      data: response.data,
    };
  } catch (error: any) {
    if (attempt < 2) {
      console.log(`HTTP Request failed, retrying attempt 2... Error: ${error.message}`);
      await new Promise(resolve => setTimeout(resolve, 1000));
      return makeHTTPRequest(config, attempt + 1);
    }
    throw error;
  }
}

export async function executeWorkflow(runId: string, startStepIndex = 0) {
  const client = await pool.connect();
  try {
    // 1. Fetch workflow run details
    const runRes = await client.query('SELECT * FROM workflow_runs WHERE id = $1', [runId]);
    if (runRes.rowCount === 0) return;
    const run = runRes.rows[0];

    // Update run status to running
    await client.query('UPDATE workflow_runs SET status = \'running\', started_at = NOW() WHERE id = $1', [runId]);

    // 2. Fetch steps
    const stepsRes = await client.query(
      'SELECT * FROM workflow_steps WHERE workflow_id = $1 ORDER BY position ASC',
      [run.workflow_id]
    );
    const steps = stepsRes.rows;

    // 3. Fetch already completed step runs outputs to build memory context
    const previousRunsRes = await client.query(
      'SELECT ws.name, sr.output FROM step_runs sr JOIN workflow_steps ws ON sr.step_id = ws.id WHERE sr.workflow_run_id = $1 AND sr.status = \'completed\'',
      [runId]
    );
    const previousOutputs: Record<string, any> = {};
    for (const row of previousRunsRes.rows) {
      previousOutputs[row.name] = row.output;
    }

    let currentIndex = startStepIndex;
    while (currentIndex < steps.length) {
      const step = steps[currentIndex];
      
      // Check if step run already exists and is completed (e.g. when resuming)
      const existingStepRunRes = await client.query(
        'SELECT * FROM step_runs WHERE workflow_run_id = $1 AND step_id = $2',
        [runId, step.id]
      );
      
      let stepRunId: string;
      let attemptCount = 1;
      
      if (existingStepRunRes.rows.length > 0) {
        const existingRun = existingStepRunRes.rows[0];
        if (existingRun.status === 'completed') {
          // Skip if already run successfully
          currentIndex++;
          continue;
        }
        stepRunId = existingRun.id;
        attemptCount = existingRun.attempt_count + 1;
        await client.query(
          'UPDATE step_runs SET status = \'running\', attempt_count = $1, updated_at = NOW() WHERE id = $2',
          [attemptCount, stepRunId]
        );
      } else {
        const insertRes = await client.query(
          'INSERT INTO step_runs (workflow_run_id, step_id, status, attempt_count, created_at, updated_at) VALUES ($1, $2, \'running\', 1, NOW(), NOW()) RETURNING id',
          [runId, step.id]
        );
        stepRunId = insertRes.rows[0].id;
      }

      // Resolve step input templates
      const resolvedConfig = resolveTemplates(step.config, previousOutputs);

      try {
        let output: any = {};
        
        switch (step.type) {
          case 'llm_call': {
            const prompt = resolvedConfig.prompt || 'Hello';
            await client.query('UPDATE step_runs SET input = $1 WHERE id = $2', [JSON.stringify({ prompt }), stepRunId]);
            output = await callLLM(prompt);
            break;
          }
          
          case 'http_request': {
            await client.query('UPDATE step_runs SET input = $1 WHERE id = $2', [JSON.stringify(resolvedConfig), stepRunId]);
            output = await makeHTTPRequest(resolvedConfig);
            break;
          }
          
          case 'db_write': {
            await client.query('UPDATE step_runs SET input = $1 WHERE id = $2', [JSON.stringify(resolvedConfig), stepRunId]);
            const writeKey = resolvedConfig.key || 'key';
            const writeValue = resolvedConfig.value || {};
            await client.query(
              'INSERT INTO workflow_data_writes (run_id, step_id, key, value, created_at) VALUES ($1, $2, $3, $4, NOW())',
              [runId, step.id, writeKey, JSON.stringify(writeValue)]
            );
            output = { success: true, key: writeKey, value: writeValue };
            break;
          }
          
          case 'notify': {
            await client.query('UPDATE step_runs SET input = $1 WHERE id = $2', [JSON.stringify(resolvedConfig), stepRunId]);
            const message = resolvedConfig.message || 'Notification';
            // Fetch organization ID of the workflow
            const wfRes = await client.query('SELECT org_id FROM workflows WHERE id = $1', [run.workflow_id]);
            const orgId = wfRes.rows[0].org_id;
            
            // Insert notification which triggers the Event Trigger
            await client.query(
              'INSERT INTO notifications (org_id, message, status, created_at) VALUES ($1, $2, \'pending\', NOW())',
              [orgId, message]
            );
            output = { success: true, message };
            break;
          }
          
          case 'conditional_branch': {
            await client.query('UPDATE step_runs SET input = $1 WHERE id = $2', [JSON.stringify(resolvedConfig), stepRunId]);
            
            // Get output of the previous step
            const lastStep = steps[currentIndex - 1];
            const lastOutput = lastStep ? previousOutputs[lastStep.name] : {};
            const conditionStr = resolvedConfig.condition || 'true';
            
            let match = false;
            try {
              // Safe evaluation using simple JS context
              const evalFn = new Function('output', 'return !!(' + conditionStr + ');');
              match = evalFn(lastOutput);
            } catch (e) {
              console.error(`Condition evaluation error:`, e);
              match = false;
            }
            
            output = { evaluated_condition: conditionStr, result: match };
            
            // Branch routing
            const targetStepId = match ? resolvedConfig.true_step_id : resolvedConfig.false_step_id;
            if (targetStepId) {
              const targetIndex = steps.findIndex(s => s.id === targetStepId);
              if (targetIndex !== -1) {
                // Save step run completion
                await client.query(
                  'UPDATE step_runs SET status = \'completed\', output = $1, updated_at = NOW() WHERE id = $2',
                  [JSON.stringify(output), stepRunId]
                );
                previousOutputs[step.name] = output;
                currentIndex = targetIndex;
                continue; // Skip standard increment and jump directly
              }
            }
            break;
          }
          
          case 'approval_gate': {
            await client.query('UPDATE step_runs SET input = $1 WHERE id = $2', [JSON.stringify(resolvedConfig), stepRunId]);
            // Pause the execution
            await client.query(
              'UPDATE step_runs SET status = \'paused\', updated_at = NOW() WHERE id = $1',
              [stepRunId]
            );
            await client.query(
              'UPDATE workflow_runs SET status = \'paused\', completed_at = NULL WHERE id = $1',
              [runId]
            );
            // End function execution (awaits manual approval Action to resume)
            return;
          }
        }

        // Save step run output
        await client.query(
          'UPDATE step_runs SET status = \'completed\', output = $1, updated_at = NOW() WHERE id = $2',
          [JSON.stringify(output), stepRunId]
        );
        previousOutputs[step.name] = output;
        currentIndex++;
        
      } catch (stepError: any) {
        console.error(`Step ${step.name} failed:`, stepError.message);
        
        await client.query(
          'UPDATE step_runs SET status = \'failed\', error = $1, updated_at = NOW() WHERE id = $2',
          [stepError.message, stepRunId]
        );
        
        await client.query(
          'UPDATE workflow_runs SET status = \'failed\', completed_at = NOW() WHERE id = $1',
          [runId]
        );
        return; // Stop workflow run
      }
    }

    // 4. Completed all steps successfully
    await client.query(
      'UPDATE workflow_runs SET status = \'completed\', completed_at = NOW() WHERE id = $1',
      [runId]
    );

    // 5. Increment organization usage quota
    const wfRes = await client.query('SELECT org_id FROM workflows WHERE id = $1', [run.workflow_id]);
    if (wfRes.rows.length > 0) {
      const orgId = wfRes.rows[0].org_id;
      await client.query('UPDATE organizations SET quota_usage = quota_usage + 1 WHERE id = $1', [orgId]);
    }

  } catch (err) {
    console.error('Executor transaction error:', err);
  } finally {
    client.release();
  }
}
